### ISSUE TITLE
Big image is not shown in Android 4

### ISSUE THREAD

**Issue by urmat-okonov** [coil-kt/coil#525] opened 2020-09-07 09:32 UTC
**Describe the bug**
The problem was described in https://stackoverflow.com/questions/63773543/coil-is-not-working-with-big-images-in-android-4-4

**Expected behavior**
The big image(for example 900x350) should be shown in version of Android 4 

**To Reproduce**
Create a project with imageView, use Coil Library and load Android 4 (API 19). Use big image like this: 

`imageView.load("https://www.giveacare.com.au/wp-content/uploads/2020/02/ABC-PM-1024x537.jpg")`

**Logs/Screenshots**

| How it should work | Present behaviour |
----------------|----------------|
![Screenshot_1599530125](https://user-images.githubusercontent.com/56011185/92425316-aef03900-f1a8-11ea-80f2-22d66c66fac3.png) | ![Screenshot_1599530127](https://user-images.githubusercontent.com/56011185/92425318-b0b9fc80-f1a8-11ea-8a61-ba131fe5e9bc.png)

**Version**
io.coil-kt:coil:0.11.0 
Android 4 API 19

**Comment by colinrtwhite** [comment] 2020-09-07 19:21
I'm not able to reproduce this using the `coil-sample` app. Maybe it's an issue with your local dev environment? [Try checking the logs](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging).

<img src="https://user-images.githubusercontent.com/5580160/92413336-8c650e00-f11d-11ea-84b9-9a09bddc59c3.png" width=50%/>

**Comment by urmat-okonov** [comment] 2020-09-08 01:54
> I'm not able to reproduce this using the `coil-sample` app. Maybe it's an issue with your local dev environment? [Try checking the logs](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging).
> 
> <img alt="" width="25%/" src="https://user-images.githubusercontent.com/5580160/92413336-8c650e00-f11d-11ea-84b9-9a09bddc59c3.png">

Sorry I sent the wrong url, please try this one: 

`imageView.load("https://www.giveacare.com.au/wp-content/uploads/2020/02/ABC-PM-1024x537.jpg")`

The result:
![Screenshot 2020-09-08 at 7 52 37](https://user-images.githubusercontent.com/56011185/92425253-836d4e80-f1a8-11ea-8b50-0aba74fde277.png)

**Comment by colinrtwhite** [comment] 2020-09-08 02:08
Using `DebugLogger` I was able to see this error in the logs: `java.net.ConnectException: Failed to connect to www.giveacare.com.au/2606:4700:3033::681b:97cc:443`. This means the device was unable to connect to the server - likely because it only supports TLS 1.2+, which Android 4.x does not. Closing as this is not a bug with Coil.

**Comment by colinrtwhite** [comment] 2020-09-08 02:08
Using `DebugLogger` I was able to see this error in the logs: `java.net.ConnectException: Failed to connect to www.giveacare.com.au/xyz:443`. This means the device was unable to connect to the server - likely because it only supports TLS 1.2+, which Android 4.x does not. Closing as this is not a bug with Coil.

**Closed by colinrtwhite** 2020-09-08 02:08 UTC
Labels: bug
