### ISSUE TITLE
VideoFrameDecoder HLS Support

### ISSUE THREAD

**Issue by myounis97** [coil-kt/coil#2145] opened 2024-02-27 08:46 UTC
Hello is it possible to make VideoFrameDecoder support HLS URLs thanks

**Comment by rustamsmax** [comment] 2024-02-27 12:04
I think coil video loader was intended to be used for basic gif/mpeg4 loading
For loading advanced videos you can use platform specific apis
For android: Exoplayer
For ios: AVPlayer
For desktop: vlcj

**Comment by myounis97** [comment] 2024-02-27 12:15
> I think coil video loader was intended to be used for basic gif/mpeg4 loading
> 
> For loading advanced videos you can use platform specific apis
> 
> For android: Exoplayer
> 
> For ios: AVPlayer
> 
> For desktop: vlcj

VideoFrameDecoder is used to get a thumbnail at specific time it works well with mp4 am not using it to load a video i'm already using ExoPlayer for video playing but I'm implementing thumbnail seeking feature to display the thumbnail while seeking

**Comment by rustamsmax** [comment] 2024-02-27 12:26
Why not to store the thumbnail in the server and pass data with url to this thumbnail?

**Comment by colinrtwhite** [comment] 2024-02-27 18:53
+1 to @rustamsmax said. Unfortunately I think this is out of scope for `VideoFrameDecoder` as the underlying class Coil uses to decode video frames, `MediaMetadataRetriever`, doesn't support HLS streams. This means to add support we would either have to write our own HLS stream parser (not easy!) or likely import FFMPEG, which is large as it includes native libraries. Your best bet is to use ExoPlayer on Android if you can't have the server expose the thumbnail.

**Closed by colinrtwhite** 2024-02-27 18:53 UTC
Labels: enhancement
