### ISSUE TITLE
trying to use a recycled bitmap

### ISSUE THREAD

**Issue by yyg20101** [coil-kt/coil#504] opened 2020-08-25 08:49 UTC
This is a very occasional error, how can I troubleshoot

java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@a8bb2a5
        at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:87)
        at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:278)
        at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:91)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
        at android.widget.ImageView.onDraw(ImageView.java:1434)
        at android.view.View.draw(View.java:23190)
        at android.view.View.updateDisplayListIfDirty(View.java:22065)
        at android.view.View.draw(View.java:22920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1882)
        at android.view.View.draw(View.java:23193)
        at android.view.View.updateDisplayListIfDirty(View.java:22065)
        at android.view.View.draw(View.java:22920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
        at android.view.View.updateDisplayListIfDirty(View.java:22051)
        at android.view.View.draw(View.java:22920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
        at android.view.View.updateDisplayListIfDirty(View.java:22051)
        at android.view.View.draw(View.java:22920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
        at android.view.ViewOverlay$OverlayViewGroup.dispatchDraw(ViewOverlay.java:254)
        at android.view.View.draw(View.java:23193)
        at android.view.View.updateDisplayListIfDirty(View.java:22059)
        at android.view.View.draw(View.java:22920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1882)
        at android.view.View.updateDisplayListIfDirty(View.java:22051)
        at android.view.View.draw(View.java:22920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
        at android.view.View.updateDisplayListIfDirty(View.java:22051)
        at android.view.View.draw(View.java:22920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
        at android.view.View.updateDisplayListIfDirty(View.java:22051)
        at android.view.View.draw(View.java:22920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
        at android.view.View.updateDisplayListIfDirty(View.java:22051)
        at android.view.View.draw(View.java:22920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
        at android.view.View.updateDisplayListIfDirty(View.java:22051)
        at android.view.View.draw(View.java:22920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
        at android.view.View.draw(View.java:23193)
        at com.android.internal.policy.DecorView.draw(DecorView.java:1118)
        at android.view.View.updateDisplayListIfDirty(View.java:22065)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:588)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:594)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:667)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:4263)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4047)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3320)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2200)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9037)
E/AndroidRuntime:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
        at android.view.Choreographer.doCallbacks(Choreographer.java:797)
        at android.view.Choreographer.doFrame(Choreographer.java:732)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8034)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

**Comment by colinrtwhite** [comment] 2020-08-25 18:08
Which version of Coil are you using? There were fixes for this issue in `0.12.0`.

**Comment by yyg20101** [comment] 2020-08-26 01:50
> Which version of Coil are you using? There were fixes for this issue in `0.12.0`.

The version I am currently using is 0.12.0, and I have also tried 1.0.0-rc1, but this problem occurs occasionally

**Comment by colinrtwhite** [comment] 2020-08-26 18:22
Hmm it's tough to debug exactly without a sample app. If it's easier, you can disable bitmap pooling with `ImageLoader.Builder.bitmapPoolingEnabled(false)`.

**Comment by alcere** [comment] 2020-08-31 07:44
I saw the same issue in a very small portion of users, impossible to reproduce in my end. Only affecting pixel users so far.

**Comment by phantomVK** [comment] 2020-09-01 06:51
If there is any possible that a bitmap created by user was added to BitmapPool of Coil, then the bitmap recycled when it still in caching? In this position, add a check about `bitmap.isRecycled()` inside`RealBitmapPool.getDirtyOrNull()` is needed.

**Comment by colinrtwhite** [comment] 2020-09-07 19:46
@phantomVK Coil [invalidates any bitmaps](https://github.com/coil-kt/coil/blob/master/coil-base/src/main/java/coil/bitmap/BitmapReferenceCounter.kt#L99) that it doesn't create so they aren't returned to the pool.

**Comment by colinrtwhite** [comment] 2020-09-07 19:50
Closing this issue since it isn't actionable. If you're able to reproduce the issue, please open a new bug report. Optionally, you can also disable automatic bitmap pooling using [`bitmapPoolingEnabled(false)`](https://coil-kt.github.io/coil/api/coil-base/coil/-image-loader/-builder/bitmap-pooling-enabled/).

**Closed by colinrtwhite** 2020-09-07 19:50 UTC
Labels: question

**Comment by kavinAndro2709** [comment] 2025-12-11 21:57
i am also facing the issue in my coil v2.7.0. is there any blog, which has explanation? why this error happens? i need to know why?
