### ISSUE TITLE
Transformation with colorFilter not working correctly

### ISSUE THREAD

**Issue by MFlisar** [coil-kt/coil#581] opened 2020-11-13 07:02 UTC
**Describe the bug**

* use a vector drawable that contains a tint with alpha value (it's just with what I found this issue, I did not test if this is the necessary)
* tint the image with a solid `PorterDuffColorFilter`
* the alpha value is not replaced correctly by the tint color

**Expected behavior**

The image should be tinted correctly - this means the filter should be applied as defined => SRC_IN should replace all existing pixels in the image with the provided color e.g.

**To Reproduce**

Code:
* test activity with all code: [here](https://github.com/MFlisar/tests/blob/master/app/src/main/java/com/michaelflisar/tests/tests/imageTintTest/ImageTintTestActivity.kt)
* drawable (it's the default one added via android studio): [here](https://github.com/MFlisar/tests/blob/master/app/src/main/res/drawable/ic_baseline_mail_outline_24.xml)

Here's the main code from the example:

```kotlin

val color = Color.WHITE
val mode = PorterDuff.Mode.SRC_IN
		
// Variant 1
binding.iv1.setImageResource(testImage)
binding.iv1.colorFilter = PorterDuffColorFilter(color, mode)

// Variant 2
binding.iv2.setImageResource(testImage)
binding.iv2.drawable.colorFilter = PorterDuffColorFilter(color, mode)

// Variant 3
binding.iv3.load(testImage) {
	transformations(ColorTintTransformation(color, mode))
}
```

The `ColorTintTransformation` class is part of the link above, it's a simple transformation that does apply the filter on the bitmap with the help of the paint...

**Logs/Screenshots**

![image-tint-test](https://user-images.githubusercontent.com/2437726/99039552-d20fde00-2587-11eb-9d12-c4d0c07a9e83.png)
![image-tint-test](https://user-images.githubusercontent.com/2437726/99039714-21560e80-2588-11eb-8832-96f001c0bc9f.png)

**Version**

1.0.0

**Comment by colinrtwhite** [comment] 2020-11-22 05:28
@MFlisar Thanks for the report. I think is due to the fact that the first two variants apply the colour filter directly on the drawable whereas using a `Transformation` to apply the colour filter requires converting the vector drawable to a bitmap drawable before applying the colour filter. Unfortunately, I don't think it's possible to fix/change this behaviour since `Transformation`s take a bitmap as input.

**Comment by MFlisar** [comment] 2020-11-22 09:51
I was quite sure that I never faced this issue with glide so I added glide to my demo - and it works with vector drawables as well. The color transformation from glide is from [here](https://github.com/wasabeef/glide-transformations/blob/main/transformations/src/main/java/jp/wasabeef/glide/transformations/ColorFilterTransformation.java) and as you can see, code is exactly the same as in my coil transformation and simply applying the `PorterDuffColorFilter` to the provider bitmap when drawing it to the `Canvas`.

You can check out my demo again to check this and you will see it works with glide as expected.

**Comment by colinrtwhite** [comment] 2020-11-23 17:51
@MFlisar Hmm it must be something else then. Will take a look.

**Comment by anesabml** [comment] 2021-01-29 15:39
Hi, I just spend some time debugging this issue and I think it has to do with `android:tint="?attr/colorControlNormal"` in `drawable/ic_baseline_mail_outline_24.xml`.
When I tried to get the `colorControlNormal` hex code, I got `9ef`, so I tried setting the `colorControlNormal` in styles to a random colour and the colour filter worked just fine.

**Comment by cemore2048** [comment] 2021-08-21 21:30
@MFlisar do you still have the test activity with the code anywhere? Trying to repro but applying a tint with a transformation seems to be working for me

**Comment by MFlisar** [comment] 2021-08-23 05:46
@cemore2048 

Yes, it's still in there, I just restructured my test code in the meantime. Here are the links:

* [Repo](https://github.com/MFlisar/tests)
* [ImageTintTestFragment.kt](https://github.com/MFlisar/tests/blob/master/app/src/main/java/com/michaelflisar/tests/tests/coil/tinting/ImageTintTestFragment.kt)

**Comment by colinrtwhite** [comment] 2021-09-20 05:01
@cemore2048 Did you get a chance to take a look at this?

**Comment by cemore2048** [comment] 2021-09-21 03:36
@colinrtwhite not as much as I'd like. Did take a look and can reproduce getting it correct in the way anesabml was able to. But haven't looked into a solution since the inkling here is that there's still an underlying issue.

**Comment by colinrtwhite** [comment] 2021-11-19 22:43
After investigating with @cemore2048, it looks like Glide is using the application context to load the vector drawable whereas Coil uses the local activity context. This is why Glide loads the `VectorDrawable` without the tint and Coil loads it with the tint.

Both Glide and Coil then convert the vector drawable into a bitmap to perform the transformation, which bakes any tint into the bitmap. Setting the `paint.colorFilter` then applies the tint on top of the bitmap. Using `setImageResource` and `colorFilter =` doesn't bake the tint into the bitmap, which is why it's different.

Ultimately, I think Coil is working as intended in this case since using the application context to load the drawable incorrectly discards the tint and won't always resolve the correct drawable (for instance, it will be incorrect if using a separate drawable for night mode). To have it work the same as Glide, you can remove the `android:tint="?attr/colorControlNormal"` from the vector drawable's XML.

**Closed by colinrtwhite** 2021-11-19 22:43 UTC
Labels: bug, help wanted

**Comment by MFlisar** [comment] 2021-11-22 07:15
Thanks for the explanation. In general it makes sense what you say and I'd say its ok, that the tint is applied on loading the drawable before applying any custom tint.

Still, imho, I'd say it does not work as intended if it works different than what the native `ImageViews` `setImageResource` does...

Removing the tint from the xml leads to a situation where I need to duplicate images for the use in menus (here I want the tint in the xml) and in `ImageViews` where I do use coil to load the image...
