### ISSUE TITLE
Don't call onCancel for prefetched RecyclerView items.

### ISSUE THREAD

**Issue by gosr** [coil-kt/coil#542] opened 2020-09-26 10:24 UTC
Hi,
I am using `ImageRequest.Listener` to control a loading spinner in a custom `ImageView` on Android.
The purpose of the loading spinner is (if it's not obvious) to be shown when the request is in progress and before the image is loaded from a server.

I was using both `onSuccess()`, `onCancel()` and `onError()` to hide the loading spinner, because whenever the request was cancelled for some reason, or when an error occurred, I don't want to show a loading spinner, but just default back to showing a placeholder image.

However, after upgrading to version 1.0.0-rc3, it seems that `onCancel()` is being fired by the library *immediately*. This has changed from previous versions. I thought it could have something to do with images being available in cache, but I just did a test where I cleared memory and disk cache, and `onCancel()` was still being fired immediately.

What has changed, what is the cause of `onCancel()` being fired in the first place?

**Comment by colinrtwhite** [comment] 2020-09-26 17:21
This sounds like it could be related to https://github.com/coil-kt/coil/pull/518. Is your request being started on a detached view?

**Comment by gosr** [comment] 2020-09-28 06:59
@colinrtwhite yeah the loading requests are being started when binding items in a RecyclerView.

**Comment by clhols** [comment] 2020-10-01 16:36
@colinrtwhite How can a memory leak cause onCancel() to be called?

**Comment by colinrtwhite** [comment] 2020-10-07 21:46
@clhols The issue is if the request is started on a detached view in a `Fragment` (like with [`RecyclerView` prefetch](https://medium.com/google-developers/recyclerview-prefetch-c2f269075710)) it'll never have `onViewDetachedFromWindow` called, which can leak the containing `Fragment`. We need to cancel the request instantly if it's started on a detached view (I believe Glide errors in this case) to guard against this case. If the view is attached, the request will automatically restart.

Ideally, we would handle `RecyclerView` prefetch more gracefully and not cancel then restart the request. Open to ideas!

**Comment by colinrtwhite** [comment] 2022-03-07 04:14
This is fixed in `2.0.0-rc01`.

**Closed by colinrtwhite** 2022-03-07 04:14 UTC
Labels: enhancement
