### ISSUE TITLE
【coil:2.0.0-alpha05】When I load images with multiple ImageViews at the same time, only one ImageView can load the image successfully

### ISSUE THREAD

**Issue by hyx0804xiaokeai** [coil-kt/coil#1052] opened 2021-12-21 05:41 UTC
**Describe the bug**
When I use multiple ImageViews to load the same URL at the same time, only one ImageView can load the image successfully,Other ImageViews will raise an exception。**This bug is not inevitable**

**Logs/Screenshots**
![image](https://user-images.githubusercontent.com/37861965/146877309-42bbd80c-c156-4858-9588-b3f95e16f53c.png)

**Version**
coil:2.0.0-alpha05

**Comment by colinrtwhite** [comment] 2021-12-22 21:45
Do you have a code sample that reproduces the issue? I tried loading the same image at the same time in the sample app and it worked as intended:

![screen](https://user-images.githubusercontent.com/5580160/147158685-79558370-a51d-45ad-81af-ce5824dd2be3.png)

**Comment by hadiyarajesh** [comment] 2021-12-23 11:14
I also face an issue where some imageview can load the image, while others can't at the same time. though, they load it after i navigate (and come back from) other composable screen. This was not the case with version 1.3.2.

**Comment by colinrtwhite** [comment] 2021-12-28 19:55
Closing as I'm unable to reproduce.

**Closed by colinrtwhite** 2021-12-28 19:55 UTC
