### ISSUE TITLE
Coil-compose not loading image in ConstraintLayout (with unset size)

### ISSUE THREAD

**Issue by phansier** [coil-kt/coil#953] opened 2021-10-14 08:46 UTC
**Describe the bug**
Attempt to reopen https://github.com/coil-kt/coil/issues/813 with a reproducible example
Given: The Image needs to have a specified size or else the image won't be loaded. 
Seems it can be fixed, as for using ConstraintLayout is rather wide.

**To Reproduce**
See https://github.com/phansier/CoilTest
There in MainActivity two images - first with given size and loading, second - inside ConstraintLayout (same URL) - not loading

**Version**
io.coil-kt:coil-compose:1.4.0

**Comment by colinrtwhite** [comment] 2021-10-20 04:59
Thanks for the report, I agree unset sizes are currently a pain point with Coil Compose due to the way Compose doesn't call `Painter.onDraw` if a `Painter` doesn't have an exact size. I'm working on something that should hopefully handle these cases so stay tuned (no eta)!

**Comment by i-am-mani** [comment] 2021-11-05 09:49
when its hard to define image dimension or aspect ratio, I think this can be worked around by setting` minHeight=1.dp` (or width). 

```
Image(modifier = Modifier
                    .padding(4.dp)
                    .fillMaxWidth()
                    .defaultMinSize(minHeight = 1.dp),
                    painter = rememberImagePainter(images[page].src),
                    contentScale = ContentScale.Crop,
                    contentDescription = null)
```

**Comment by colinrtwhite** [comment] 2021-11-22 20:18
I've just published Coil [2.0.0-alpha04](https://github.com/coil-kt/coil/blob/main/CHANGELOG.md#200-alpha04---november-22-2021), which includes a new composable called `AsyncImage`. `AsyncImage` fixes this issue by listening to the incoming constraints instead of waiting for the canvas size in `Painter.onDraw` like with `ImagePainter`. Here's an example migration:

```kotlin
Image(
    painter = rememberImagePainter("https://example.com/image.jpg"),
    contentDescription = null
)

AsyncImage(
    model = "https://example.com/image.jpg",
    contentDescription = null
)
```

`AsyncImage` also supports setting composables for `loading`/`success`/`error` states. It's intended to replace `rememberImagePainter` in 2.x in all cases unless you need a `Painter`.

For an immediate solution to this in Coil 1.x, I'd set `rememberImagePainter(url) { size(OriginalSize) }` as setting a size skips waiting for `onDraw`.

**Comment by MrBean355** [comment] 2021-12-31 08:02
I also ran into this issue in a different scenario in Compose.
When I added `verticalScroll()` modifier to a column, the image stopped loading.
Applying the suggested fix of `size(OriginalSize)` works for me as well.
Sample code:
```kotlin
Column(
    modifier = Modifier.verticalScroll(rememberScrollState())
) {
    Image(
        painter = rememberImagePainter(data = imageUrl) {
            size(OriginalSize) // doesn't load without this line
        },
        contentDescription = null
    )
    repeat(50) {
        ListItem {
            Text("Item $it")
        }
    }
}
```

**Comment by ArthurKun021** [comment] 2022-03-18 03:17
I did some testing

I managed to show the image even with `width = Dimension.fillToConstraints` by giving `Modifier.fillMaxWidth()` to the `ConstraintLayout`

```
ConstraintLayout(
    Modifier.fillMaxWidth()
) {
    ...
```

Here's my fork of the project
[CoilTest](https://github.com/ArthurKun021/CoilTest)

also just in case, I tested all of the `ContentScale` and it works fine


`constraintlayout-compose 1.0.0`
`coil-compose 2.0.0-rc01`

**Comment by colinrtwhite** [comment] 2022-05-11 21:37
I think @mhopmann-mo is right that this is an issue (or maybe intended behaviour?) with `ConstraintLayout`. If you don't set `Modifier.fillMaxWidth()` like in @ArthurKun021's example, the `ConstraintLayout` sets the `AsyncImage`'s constraints as `Constraints.Zero`, which prevents the image from being loaded. Adding `Modifier.fillMaxWidth()` to the `ConstraintLayout` passes a correct set of dimensions to the `ConstraintLayout`'s children.

Going to close this out as I don't think there's an action to take in Coil.

**Closed by colinrtwhite** 2022-05-11 21:37 UTC
