### ISSUE TITLE
2.2.0 of Coil breaks the Relay plugin code generation

### ISSUE THREAD

**Issue by IanArb** [coil-kt/coil#1544] opened 2022-11-24 15:32 UTC
**Describe the bug**
A clear and concise description of what the bug is. **Please [enable logging](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging) and attach any stack traces.** Bug reports without reproduction steps are likely to be closed.

**To Reproduce**
Add the new Relay plugin to your Android studio Project with these [instructions](https://plugins.jetbrains.com/plugin/19721-relay-for-android-studio/)

**Logs/Screenshots**
When building the project which enables the code generation of your relay UI package imports this forces the compiler to complain about the @JvmDefaults 

`Relaybox.kt, RelayRowColumnImpl.kt`
`Inheritance from an interface with '@JvmDefault' members is only allowed with -Xjvm-default option`

**Version**
2.2.0

**Comment by colinrtwhite** [comment] 2022-11-27 06:00
Coil `2.2.0` doesn't use `JvmDefault` so I'm not sure how the relay plugin could run into issues with Coil using it. Are you sure Coil is causing these errors?

**Comment by colinrtwhite** [comment] 2022-12-04 23:45
Closing this as I'm unable to reproduce it.

**Closed by colinrtwhite** 2022-12-04 23:45 UTC
