### ISSUE TITLE
BitmapFactory returned a null Bitmap

### ISSUE THREAD

**Issue by yoesuv** [coil-kt/coil#157] opened 2019-10-29 08:28 UTC
Load image from [url like this](https://lh3.googleusercontent.com/Xne_ftCRDBiXSYXuH1XFbav-lk7xXAOvcLhtqjbdqNBKWtoamUPSkev8XaCEpPFGuAI9WqjrYHVJFSxiIQhwsu6AGSwkxw6WqEUrQizK-sxhRdUCTBx1K8wu5DnkKfADGGqKqhHHep36aGiwrJIYsn6ZT5lJ-MUgxnzwo9mMb6iASGzKctpA9zhmTjlA4jkYVlBiBrM-WaktnnDSF9lQRsdG30Hdh4fFQxq3YPWX3MmZSaCZSgvFj7CMKewj7JfCz2sOUFYlbnGWtHY0c6PenvNaOf1NygxgI6u_v2x992dLZKlTGNvyU8DyRKCNrPCG4_XVlbu-9k_YD0sjfDMO4xuBRrvt6jex7vTdw-LrgttOncCVSMIGJ9nY9dLDH2bFp2Igi-e_XzZ7615jKJDV_1FHVTLFlGhOrbIiHw2R-T9d-bGA6ubsuA3vCh-1oDXATRRh0i1Z9Q3FNeSjKZ59dfFPaHA0BrlVQm5PwWqq4vBLHlftNUoeTld6mhlmdqZapDH59x7Kym9eJAk9RXgDhCk11YtdOPwBoW5swA57313YFM8ahCAm1gG2rxU28meOZpAJAGeDJZ5lxW6nMFVw4p8pUV0mXXPqtGsCfucdLRK6dXKPDcB__tY=s962-w962-h641-no) failed,  

message from listener **BitmapFactory returned a null Bitmap**

```
W/System.err: java.lang.IllegalStateException: BitmapFactory returned a null Bitmap.
W/System.err:     at coil.decode.BitmapFactoryDecoder.decode(BitmapFactoryDecoder.kt:152)
W/System.err:     at coil.RealImageLoader$loadData$2.invokeSuspend(RealImageLoader.kt:345)
W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/System.err:     at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

**Comment by colinrtwhite** [comment] 2019-10-29 19:18
Thanks; looks like the system logs `SkAndroidCodec::NewFromStream returned null` on Android 24+. Seems like it's an issue with [`BitmapFactory.cpp`](https://stackoverflow.com/questions/39316069/bitmapfactory-decodestream-from-assets-returns-null-on-android-7). Going to leave this open for the moment to see if it can be worked around.

**Comment by JulianBissekkou** [comment] 2019-12-10 10:19
@yoesuv  Any update on this?

**Comment by yoesuv** [comment] 2019-12-11 12:25
@JulianBissekkou not yet, but move to another image hosting and works fine

**Comment by GarikKhachaturyan** [comment] 2019-12-23 09:35
Same with me

**Comment by mario** [comment] 2020-01-05 19:34
I think the behaviour of Coil here is correct. While there is an image returned by the URL, it is accompanied by HTTP code 403 with a meaning of Forbidden. Success would mean a code between 200 and 300. So I'd leave the behaviour as-is, but it's up to @colinrtwhite to decide what to do.

**Comment by mario** [comment] 2020-01-05 19:44
Update: actual value returned is HTML, not an image. So behaviour of Coil is indeed correct. 
I'd suggesting closing the issue.

**Comment by colinrtwhite** [comment] 2020-01-06 19:59
@mario Interesting - I could have sworn the URL used to return an `image/png` content type. In the future we should host any images on Github to prevent their content changing. Thanks for taking a look.

@yoesuv If you're able to reproduce this with another image please reopen this issue or create another one.

**Closed by colinrtwhite** 2020-01-06 19:59 UTC
Labels: bug, help wanted

**Comment by mario** [comment] 2020-01-06 20:06
@colinrtwhite the hypothesis that it was indeed the same issue in the past is furthered by the fact that the issue for the same image disappeared for the initial poster after he moved to another hosting.

But who knows ... we might never find out :)

**Comment by asarazan** [comment] 2020-02-07 04:07
Hey sorry to dig this up, but can you provide guidance on how to go about catching these exceptions? It's pretty far out in the callstack, so I guess just set an exception handler for Dispatchers.IO or something?

Thanks!

**Comment by colinrtwhite** [comment] 2020-02-07 04:30
@asarazan This shouldn't crash your app if it occurs as part of a `load` call. It's likely causing a crash if you launch a `get` call inside of your `CoroutineScope` and don't set a `CoroutineExceptionHandler`. Surrounding the call in a `try/catch` solves this: https://github.com/Kotlin/kotlinx.coroutines/blob/master/docs/exception-handling.md#exceptions-aggregation

**Comment by asarazan** [comment] 2020-02-07 05:24
Ah that was it. I forgot about a raw `get` call that I had added in a recent refactor. Thanks!
