### ISSUE TITLE
Support loading an image directly into an bitmap (without constructing the wrapper drawable)

### ISSUE THREAD

**Issue by halizton** [coil-kt/coil#1311] opened 2022-06-03 18:59 UTC
**Is your feature request related to a problem? Please describe.**
My use case is that we need to draw a bitmap onto the canvas directly. Looking at the current coil API, the image is loaded into a BitmapDrawable. We can get the bitmap from the BitmapDrawable, there's no problem. But in our case, the BitmapDrawable unnecessarily acquire extra memory.

We are currently migrating from Picasso into Coil and we are an image heavy application. Because of the lack of API to load a bitmap directly, we experienced more OOM errors when using Coil comparing to using Picasso.

I was looking at the BitmapFactoryDecoder and looks like the DecodeResult has to carry a Drawable, but later in transformation phase, we only need to manipulate the bitmap inside the drawable and construct a new drawable from the transformed bitmap. I am not sure I fully follow the logic, but would it be more efficient if we construct the drawable at the end of the image loading pipeline (right before delivering the result to the user). Also whether or not constructing a drawable with the final bitmap can be configurable.

```
        return withContext(request.transformationDispatcher) {
            val input = convertDrawableToBitmap(result.drawable, options, transformations)
            eventListener.transformStart(request, input)
            val output = transformations.foldIndices(input) { bitmap, transformation ->
                transformation.transform(bitmap, options.size).also { ensureActive() }
            }
            eventListener.transformEnd(request, output)
            result.copy(drawable = output.toDrawable(request.context))
        }
```

**Describe the solution you'd like**
Let the BitmapFactoryDecoder decode the image stream directly into a bitmap instead of constructing a drawable if the user request so. This can be configured at the request level.

**Additional context**

**Comment by colinrtwhite** [comment] 2022-06-04 18:18
`BitmapDrawable` is a small wrapper for a `Bitmap` that takes very little extra memory. I'd be very surprised if it was the cause of your OOMs. Have you profiled your app to find out if this is the cause of the OOMs?

**Comment by halizton** [comment] 2022-06-05 00:23
I only see increased OOM errors and memory warnings when running experiments (picasso vs. coil) in production and have not yet profiled the application locally to tease out the cause of the OOMs. I will do that and in the mean time, do you have any suggestions that anything could have gone wrong usually when using Coil?

One thing that is special in my use case is: since I only need bitmap, so I keep a reference to the bitmap that returned from the `Target` and deliver it to my application layer along with the `Listener::onSuccess()` callback. I assume that won't cause any issues.

I attached my coil integration below for your reference:

```
var rc: ImageRequest.Builder = ImageRequest.Builder(context)
val headersBuilder = Headers.Builder()
buildRequestHeaders(headers).forEach { (key, value) ->
    headersBuilder.add(key, value)
}
rc.headers(headersBuilder.build())

if (targetHeight != 0 && targetWidth != 0) {
    // Note: coil's size + Precision.EXACT does not work as expected, using a transformation if resize
    //       further if coil could not give us the exact resolution requested.
    rc.size(targetWidth, targetHeight)
    if (doTransformation) {
        rc.transformations(
            ResizeTransformation(
                targetWidth, targetHeight, onlyScaleDown = false, centerCrop = true
            )
        )
    }
} else {
    // Note: this helps reducing the bitmap sizes showing on the screen, could reduce the memory pressure
    if (doTransformation) {
        rc.safeScaleDown(centerCrop)
    }
}

bitmapConfig?.apply {
    rc.bitmapConfig(this)
}
placeHolder?.apply {
    rc.placeholder(this)
}
rc.allowHardware(ImageUtils.isInCoilAllowHardware)
val imageTag = cachableImage.imageTag
if (imageTag != null) {
    rc = rc.tag(imageTag)
}

var bitmapTmp: Bitmap? = null
rc.target {
    bitmapTmp = (it as BitmapDrawable).bitmap
}

rc.listener(
    onError = { _, _ ->
        removeImageRequestRecord(cachableImage)
        cachableImage.onBitmapFailed(null)
    },
    onSuccess = { request, result ->
        (request.data as? String)?.apply {
            result.memoryCacheKey?.let { memoryKeysMap[this] = it }
        }
        removeImageRequestRecord(cachableImage)
        cachableImage.onBitmapLoaded(bitmapTmp, result.dataSource.toLoadedFrom(), null)
    }
)
rc.data(url)

val request = rc.build()
context.imageLoader.enqueue(request).let {
    url?.apply {
        requestMap[cachableImage.hashCode()] = it
    }
}
```

**Comment by colinrtwhite** [comment] 2022-06-05 01:31
Do you clear disposables in the request map at any point? That holds a reference to the final success/error image.

**Comment by colinrtwhite** [comment] 2022-06-05 01:37
Also I’m curious why ResizeTransformation is required? What are the expected output dimensions given a target width and height? Using a transformation disables several optimizations.

**Comment by halizton** [comment] 2022-06-05 02:57
> Do you clear disposables in the request map at any point? That holds a reference to the final success/error image.

The `removeImageRequestRecord()` method will clear the disposable and it is called for both success and error cases. Will all image requests end up in either success or error cases? I am wondering if there are cases where we would leak the disposables.

```
    private fun removeImageRequestRecord(cachableImage: CachableImage?) {
        cachableImage?.hashCode()?.let { key ->
            requestMap[key]?.dispose()
            requestMap.remove(key)
        }
    }
```

**Comment by halizton** [comment] 2022-06-05 03:02
> Also I’m curious why ResizeTransformation is required? What are the expected output dimensions given a target width and height? Using a transformation disables several optimizations.

I see, I need `ResizeTransformation` to make sure the result bitmap hold the exact resolution as specified by `size(width, height)` since using `size` only can not guarantee the exact outgoing resolution. Actually it is not absolutely needed in the application, it's just because the Picasso integration works that way and we have some tests to guard again the outgoing resolutions, so initially I'd like to achieve the same with Coil.

I can definitely run a test in production without the transformation to see if there's any improvement in OOM issues and loading speed issues.

> Using a transformation disables several optimizations

Mind to point out what optimizations will be disabled when a transformation is used?

**Comment by colinrtwhite** [comment] 2022-06-05 03:15
The image request can be cancelled as well.

Transformations disable using hardware bitmaps. Hardware bitmaps consume much less memory and are drawn faster.

**Comment by colinrtwhite** [comment] 2022-06-05 03:17
Going to close this out since it doesn’t appear to be a bug internally in Coil.

**Closed by colinrtwhite** 2022-06-05 03:17 UTC
Labels: enhancement
