### ISSUE TITLE
Support for Gif and video repeat count along with gif finish and start listener.

### ISSUE THREAD

**Issue by pabhi66** [coil-kt/coil#724] opened 2021-04-09 17:47 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
There's no way to control gif and video loop. Also there's no way to detect video and gif end

**Describe the solution you'd like**

Adding support for gif and video repeat count would be great. Also a listener for when the gif or video starts and finishes playing.

**Additional context**

**Comment by colinrtwhite** [comment] 2021-04-10 23:21
Duplicate of https://github.com/coil-kt/coil/issues/606. This will be added in `1.2.0`.

**Closed by colinrtwhite** 2021-04-10 23:21 UTC
Labels: enhancement
