### ISSUE TITLE
Images cropped while load for the first time in recycler view if I kept scrolling

### ISSUE THREAD

**Issue by Omar-Alnajjar** [coil-kt/coil#716] opened 2021-04-02 14:47 UTC
**Describe the bug**
I have some images cropped when loading them for the first time and kept scrolling while loading

**Expected behavior**
All Images should be fully loaded

**To Reproduce**
Load about 10 images in recycler view and start scrolling

**Logs/Screenshots**
Screen record: https://drive.google.com/file/d/1zBgkdsWDcEoFWy8FU66Uud0VTgF9j_pJ/view?usp=sharing

**Version**
I am on version 1.1.1 , It was tested on android 10

**Comment by ashishmahla** [comment] 2021-04-03 14:35
I am also using an image view like this:

    <ImageView
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:adjustViewBounds="true"
                    android:minHeight="300dp"
                    android:scaleType="fitXY"
                    app:layout_constraintEnd_toEndOf="parent"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintTop_toTopOf="parent" />

And it is also cropping images when images are not preloaded. In my case, it is taking the minHeight and not adjusting image bounds when the image completes loading. Is it the same issue or can I fix this some other way if it's not?

**Comment by colinrtwhite** [comment] 2021-04-05 19:16
@Omar-Alnajjar I'm not able to reproduce this in the `coil-sample` app which loads images in a list. What's the best way for me to reproduce this? It's likely this is related to how your XML layout is set up.

@ashishmahla You should set `size(OriginalSize)` explicitly on your request if you don't want it to use the size of the `ImageView`.

**Comment by ashishmahla** [comment] 2021-04-05 19:23
@colinrtwhite But when the image loads from the cache, at that time it is working fine, issue is only when image loads later on from the network.

Also, I am using the same `adjustViewBounds` in a horizontal recyclerview with fixed height. There it is working fine but here in this scenario with fixed width and variable height I am running into this issue.

**Comment by xanscale** [comment] 2021-04-20 08:16
same problem here, in my case seams that appen only if I use placeholder

**Comment by daryljodanny** [comment] 2021-04-23 16:34
Hi, I'm also having the same issue as well.

[Here](https://drive.google.com/drive/folders/1YRF8p-v6dxHCvipAmlLkhDnMiD32IuHz) is the drive folder which consists of the sample code as well as a screen record which showcases the issue

**Comment by xanscale** [comment] 2021-04-24 14:59
same problem here. i can confirm that appen only first time (so is from network and not cache) and using placeholder.

**Comment by colinrtwhite** [comment] 2021-05-05 23:13
@daryljodanny Thanks for the the project. In your project the `ImageView` uses `scaleType="fitXY"` which is why you're seeing the behaviour in the video. `fitXY` requests that the image is stretched without maintaining aspect ratio to fit the view.

The first time the image is loaded it's wrapped in a `CrossfadeDrawable` which can't support stretching the image. The second time it's loaded it's not wrapped (since it's loaded from the memory cache) and it will be stretched by the `ImageView`. This is intended behaviour in both cases. To fix your project you can use `scaleType="centerCrop"`.

That said, it doesn't look like `fitXY` is used in the video linked in the original post. @Omar-Alnajjar if you have a way for me to reproduce your issue please attach it to this thread.

**Comment by daryljodanny** [comment] 2021-05-06 05:17
@colinrtwhite But I need `fitXY` for the images. Is there any way to load the images with `scaleType="fitXY` ?

**Comment by colinrtwhite** [comment] 2021-05-06 05:30
@daryljodanny You can disable crossfading.

**Comment by daryljodanny** [comment] 2021-05-06 05:43
Disabling  crossfade did it for me. Thanks
Ya the better solution would be to adjust the dimensions of the ImageView according to the images coming from the backend. But too bad the client isn't up for that.

I've yet another question. I was messing with Glide and came accross [this SO post](https://stackoverflow.com/a/32887693/13532511). So in coils case, should I pass a coil instance (or something) to the adapter and then use that to load the image in `onBindViewHolder` or can I simply use a `bindingAdapter`? The app which I'm about to implement uses `navGraph` and has a recyclerView with 7 view types

**Comment by ashishmahla** [comment] 2021-05-06 05:44
@colinrtwhite this doesn't seem like a solution, disabling crossfade to make it work. Why doesn't crossfade not support this?

Also, I am using `adjustViewBounds`, to stretch the image view in the variable dimension. It doesn't stretch the image. I can't possibly have a constant image view. I need one of the sides to be dynamic. Is there no way for it to work with crossfade? Can't crossfade be updated to support this? What's stopping us? :)

**Comment by colinrtwhite** [comment] 2021-05-06 08:09
@daryljodanny If you'd like the image to dictate the size of the `ImageView` you can use a combination of `size(OriginalSize)` and `adjustViewBounds=true`. However, keep in mind that this will cause the `ImageView` to change size since it's not possible to know the image's dimensions before it's downloaded + decoded. For your second question, you don't need to do anything special; you can use `load` as normal in your adapter. Coil has special logic to determine the correct lifecycle for your request.

@ashishmahla It sounds like your issue may be different if it doesn't use `fitXY`. To have one of the sides be dynamic, you should be able to set it to `wrap_content`. Please open a new issue with a repro project if you believe there's bug.

Coil's scaling system only supports two types: `FIT` and `FILL` for simplicity. `fitXY` changes the image's aspect ratio which would introduce a lot of extra complexity (internally and for the user). Glide also doesn't support `fitXY` for the same reasons.

If you really want your image to conform to the `ImageView`'s dimensions, you could write a custom [`Transformation`](https://coil-kt.github.io/coil/transformations/) for this.

**Comment by ashishmahla** [comment] 2021-05-06 08:58
> I am also using an image view like this:
> 
>     <ImageView
>                     android:layout_width="0dp"
>                     android:layout_height="wrap_content"
>                     android:adjustViewBounds="true"
>                     android:minHeight="300dp"
>                     android:scaleType="fitXY"
>                     app:layout_constraintEnd_toEndOf="parent"
>                     app:layout_constraintStart_toStartOf="parent"
>                     app:layout_constraintTop_toTopOf="parent" />
> 
> And it is also cropping images when images are not preloaded. In my case, it is taking the minHeight and not adjusting image bounds when the image completes loading. Is it the same issue or can I fix this some other way if it's not?


@colinrtwhite look at the first comment in this issue, I am using `adjustViewBounds` with `wrap_content` and `fitXY`. And that is not working out for me. I will try out what you just suggested and let you know.

**Comment by colinrtwhite** [comment] 2021-05-06 18:57
Going to close this out since I can't reproduce the initial issue without a reproduction project.

**Closed by colinrtwhite** 2021-05-06 18:57 UTC
Labels: bug, needs info

**Comment by daryljodanny** [comment] 2021-05-06 18:58
Well you can use mine right?
It shows the issue while enabling crossfade

**Comment by colinrtwhite** [comment] 2021-05-06 21:58
@daryljodanny Your project is expected behaviour and different from the issue @Omar-Alnajjar reported.
