### ISSUE TITLE
Error loading .svg image in Jetpack Compose for Desktop

### ISSUE THREAD

**Issue by jdsdhp** [coil-kt/coil#2330] opened 2024-06-24 16:37 UTC
**Describe the bug**
I am trying to load an image of type .svg in my app, but it is not allowed, and it returns an error in the onError callback. I am using Jetpack Compose for Desktop. Details are attached below.

**To Reproduce**
```
AsyncImage(
                    modifier = Modifier
                        .size(50.dp)
                        .padding(all = Paddings.tiny)
                        .clip(shape = MaterialTheme.shapes.small)
                        .border(
                            width = 2.dp,
                            color = MaterialTheme.colors.onSurface,
                            shape = MaterialTheme.shapes.small,
                        ),
                    model = workspace.avatar,
                    contentDescription = "Avatar",
                    placeholder = painterResource(Res.drawable.ic_image_placeholder),
                )
```

**Logs/Screenshots**
`Error(painter=null, result=ErrorResult(image=null, request=ImageRequest(context=coil3.PlatformContext$Companion$INSTANCE$1@7a121de9, data=https://bitbucket.org/workspaces/my-company/avatar/?ts=1715362523, target=coil3.compose.AsyncImagePainter$updateRequest$$inlined$target$default$1@39b9e0d1, listener=null, memoryCacheKey=null, memoryCacheKeyExtras={}, diskCacheKey=null, fileSystem=NioSystemFileSystem, fetcherFactory=null, decoderFactory=null, interceptorDispatcher=Dispatchers.Main.immediate, fetcherDispatcher=Dispatchers.IO, decoderDispatcher=Dispatchers.IO, memoryCachePolicy=ENABLED, diskCachePolicy=ENABLED, networkCachePolicy=ENABLED, placeholderMemoryCacheKey=null, placeholderFactory=interface kotlin.jvm.functions.Function1, errorFactory=interface kotlin.jvm.functions.Function1, fallbackFactory=interface kotlin.jvm.functions.Function1, sizeResolver=coil3.compose.internal.ConstraintsSizeResolver@136a3a04, scale=FIT, precision=INEXACT, extras=Extras(data={}), defined=Defined(interceptorDispatcher=null, fetcherDispatcher=null, decoderDispatcher=null, memoryCachePolicy=null, diskCachePolicy=null, networkCachePolicy=null, placeholderFactory=interface kotlin.jvm.functions.Function1, errorFactory=interface kotlin.jvm.functions.Function1, fallbackFactory=interface kotlin.jvm.functions.Function1, sizeResolver=coil3.compose.internal.ConstraintsSizeResolver@136a3a04, scale=FIT, precision=INEXACT), defaults=Defaults(fileSystem=NioSystemFileSystem, interceptorDispatcher=Dispatchers.Main.immediate, fetcherDispatcher=Dispatchers.IO, decoderDispatcher=Dispatchers.IO, memoryCachePolicy=ENABLED, diskCachePolicy=ENABLED, networkCachePolicy=ENABLED, placeholderFactory=interface kotlin.jvm.functions.Function1, errorFactory=interface kotlin.jvm.functions.Function1, fallbackFactory=interface kotlin.jvm.functions.Function1, precision=AUTOMATIC, extras=Extras(data={coil3.Extras$Key@133df82=kotlin.Unit}))), throwable=java.lang.IllegalArgumentException: Failed to Image::makeFromEncoded))`

**Version**
```
    val coilVersion = "3.0.0-alpha06"
    implementation("io.coil-kt.coil3:coil-compose:$coilVersion")
    implementation("io.coil-kt.coil3:coil-compose-core:$coilVersion")
    implementation("io.coil-kt.coil3:coil-network-ktor:$coilVersion")
    implementation("io.coil-kt.coil3:coil:$coilVersion")
```

**Comment by colinrtwhite** [comment] 2024-06-24 19:13
Can you post the failing image? `java.lang.IllegalArgumentException: Failed to Image::makeFromEncoded)` implies that the underlying Skia decoder failed to decode the image.

**Comment by jdsdhp** [comment] 2024-06-24 19:34
Hi @colinrtwhite, thank you for your response. Later, I did some tests with other svg files, obtaining the same reslt. I believe this is not a bug caused by this specific svg image.

![workspace_code](https://github.com/coil-kt/coil/assets/48694562/cea4ea91-968b-44c1-90cd-dd64b77408f6)

**Comment by colinrtwhite** [comment] 2024-06-26 16:17
Does the image fail to decode when using the `SVGDom` class directly ([see here](https://github.com/coil-kt/coil/blob/main/coil-svg/src/nonAndroidMain/kotlin/coil3/svg/SvgDecoder.nonAndroid.kt#L34))? If so the issue is with the underlying decoder and will need to be fixed in [Skiko](https://github.com/JetBrains/skiko).

**Comment by colinrtwhite** [comment] 2024-07-02 17:24
Looks like this is an underlying issue with the `SVGDom` class. Please file the issue with Skiko or Skia.

**Closed by colinrtwhite** 2024-07-02 17:24 UTC
