### ISSUE TITLE
GIF-image not displayed properly

### ISSUE THREAD

**Issue by GeniusRUS** [coil-kt/coil#18] opened 2019-08-13 10:08 UTC
**Describe the bug**
When displaying GIF images, previous frames are not deleted

**To Reproduce**
1. Add `io.coil-kt:coil-gif` to dependencies
2. Try to load this GIF-file:
![success](https://user-images.githubusercontent.com/24453308/62932870-05d2e580-bdd2-11e9-833a-87d26d36c3b2.gif)
3. GIF is loaded and animating but it's noticeable that the image layers remain and do not disappear (static screenshot of this behavior):
![2019_08_13_13_57_58~2](https://user-images.githubusercontent.com/24453308/62933094-85f94b00-bdd2-11e9-9c8c-2d7d5aeba44e.jpg)

Reproduces on device LG V30+ (Android 8.0 Stock)

**Expected behavior**
Previous GIF images will disappear after changing the frame

**Logs/Screenshots**
Usage:
<img width="611" alt="Code screenshot" src="https://user-images.githubusercontent.com/24453308/62932778-e1770900-bdd1-11e9-8f77-9afa58487164.png">
Image container:
<img width="727" alt="изображение" src="https://user-images.githubusercontent.com/24453308/62933478-5139c380-bdd3-11e9-9276-7c0cb9e72971.png">

**Library version**
Version `0.6.0`

**Comment by Jawnnypoo** [comment] 2019-08-13 15:18
Confirmed, I do see this behavior on an Android API 27 emulator as well

**Comment by colinrtwhite** [comment] 2019-08-13 18:53
Thanks for the report! Looks like it's probably and alpha issue. Going to tag this as help wanted in case someone else wants to tackle it, but I'll also take a look asap.

**Comment by colinrtwhite** [comment] 2019-08-14 07:57
Just pushed a fix. Snapshots aren't currently enabled for Coil, but I'll set them up this week. If you need the fix ASAP, you can checkout the repo and run `./install_archives.sh` to install the artifact to your `mavenLocal()`.

**Closed** 2019-08-14 08:04 UTC
Labels: bug, help wanted
