### ISSUE TITLE
IntrinsicSize.Max not work

### ISSUE THREAD

**Issue by SkyD666** [coil-kt/coil#2686] opened 2024-11-14 15:49 UTC
**Describe the bug**
AsyncImage causes the outer Modifier.height(IntrinsicSize.Max) to invalidate as follows

```kotlin
Row(modifier = Modifier.height(IntrinsicSize.Max)) {
    Column(
        modifier = Modifier
            .weight(1f)
            .padding(top = 12.dp)
            .padding(horizontal = 15.dp),
    ) {
        ...
    }
    if (!article.image.isNullOrBlank()) {
        OutlinedCard(
            modifier = Modifier
                .padding(top = 12.dp, end = 12.dp)
                .align(Alignment.CenterVertically),
        ) {
            AsyncImage(
                modifier = Modifier
                    .width(100.dp)
                    .fillMaxHeight()
                    .heightIn(min = 70.dp, max = 120.dp),
                model = article.image,
                contentScale = ContentScale.Crop,
            )
        }
    }
}
```

Expected: 
![1731599261931](https://github.com/user-attachments/assets/77308948-fe5f-4509-af5a-fcc514408837)

Actual:
![1731599249986](https://github.com/user-attachments/assets/cf112536-7283-42ac-89c2-af2ae058392b)

**Version**
Coil: 3.0.2
Compose: 1.7.5

**Comment by colinrtwhite** [comment] 2024-11-14 22:48
I think this is working as intended. `AsyncImage` will take up the `120.dp` allocated to it if the image is equal to or larger than that size.

**Comment by SkyD666** [comment] 2024-11-15 03:29
> I think this is working as intended. `AsyncImage` will take up the `120.dp` allocated to it if the image is equal to or larger than that size. What do you mean by "causes the outer Modifier.height(IntrinsicSize.Max) to invalidate"?

After setting IntrinsicSize.Max, the image height should not exceed the height of the left title and description Column.

**Comment by SkyD666** [comment] 2024-11-15 05:06
> I think this is working as intended. `AsyncImage` will take up the `120.dp` allocated to it if the image is equal to or larger than that size. What do you mean by "causes the outer Modifier.height(IntrinsicSize.Max) to invalidate"?

Coil 2.x does not have this problem

**Comment by colinrtwhite** [comment] 2024-11-15 20:50
@SkyD666 Can you add a small project that reproduces the issue? There were [fixes](https://github.com/coil-kt/coil/pull/2576) in Coil 3.0 related to intrinsic size handling so this is likely working in Coil 2.7 as a side effect of a bug.

**Comment by SkyD666** [comment] 2024-11-16 03:20
> @SkyD666 Can you add a small project that reproduces the issue? There were [fixes](https://github.com/coil-kt/coil/pull/2576) in Coil 3.0 related to intrinsic size handling so this is likely working in Coil 2.7 as a side effect of a bug.

ok

**Comment by ivaniskandar** [comment] 2024-11-19 15:29
```kotlin
@Preview
@Composable
private fun Test() {
    Surface {
        Row(modifier = Modifier.height(IntrinsicSize.Min)) {
            val bitmap = createBitmap(1000, 1000).applyCanvas {
                drawColor(Color.Red.toArgb())
            }
            AsyncImage(
                model = ImageRequest.Builder(LocalContext.current)
                    .data(bitmap)
                    .build(),
                contentDescription = null,
                contentScale = ContentScale.Crop,
                modifier = Modifier
                    .fillMaxHeight()
                    .aspectRatio(1f),
            )
            Spacer(modifier = Modifier.width(8.dp))
            Column(
                modifier = Modifier
                    .weight(1f)
                    .padding(vertical = 4.dp),
            ) {
                Text(
                    text = "Top text",
                    maxLines = 1,
                    overflow = TextOverflow.Ellipsis,
                )
                Text(
                    text = "Bottom text",
                    maxLines = 1,
                    overflow = TextOverflow.Ellipsis,
                )
            }
        }
    }
}
```

3.0.0-rc01
![image](https://github.com/user-attachments/assets/7138b3b9-ad60-4dd3-9d0c-090cd419535f)

3.0.3
![image](https://github.com/user-attachments/assets/a891e152-9a96-4e74-9eb9-fdda135b786c)

**Comment by SkyD666** [comment] 2024-11-20 01:23
> @ivaniskandar Thanks - yep I think that's the same issue and is related to [this change](https://github.com/coil-kt/coil/pull/2576). I still think this is the correct behavior as `AsyncImage`'s intrinsic size in that case should be 1000x1000 due to the bitmap it's displaying. If we remove Coil and render the `Bitmap` directly we get the same result:
> 
> ```kotlin
> Row(modifier = Modifier.height(IntrinsicSize.Min)) {
>     Image(
>         painter = remember {
>             val bitmap = createBitmap(500, 500).applyCanvas {
>                 drawColor(Color.Red.toArgb())
>             }
>             BitmapPainter(bitmap.asImageBitmap())
>         },
>         contentDescription = null,
>         modifier = Modifier
>             .fillMaxHeight()
>             .aspectRatio(1f),
>     )
>     Spacer(modifier = Modifier.width(8.dp))
>     Column(
>         modifier = Modifier
>             .weight(1f)
>             .padding(vertical = 4.dp),
>     ) {
>         BasicText(
>             text = "Top text",
>             maxLines = 1,
>             overflow = TextOverflow.Ellipsis,
>         )
>         BasicText(
>             text = "Bottom text",
>             maxLines = 1,
>             overflow = TextOverflow.Ellipsis,
>         )
>     }
> }
> ```
> 
> That said, I'm not sure how to nicely reproduce the original behaviour where `AsyncImage` didn't enforce its intrinsic size inside a container. You might have to use a custom `Layout` that overrides a composable's intrinsic size.

Try to change `IntrinsicSize.Min` to `IntrinsicSize.Max` ?

**Comment by colinrtwhite** [comment] 2024-11-25 05:15
@SkyD666 `IntrinsicSize.Max` produces the same result.

**Comment by ivaniskandar** [comment] 2024-11-25 05:26
Yeah so I ended up adjusting my layouts so consider my issue solved. Thanks for the confirmation!

**Comment by colinrtwhite** [comment] 2024-11-25 08:08
Ok thanks. I'm going to close this as working as intended as it matches the behaviour of `Image`.

**Closed by colinrtwhite** 2024-11-25 08:08 UTC

**Comment by SkyD666** [comment] 2024-11-25 11:34
> @SkyD666 `IntrinsicSize.Max` produces the same result.

If I change Image to Box, there is no problem: 

```kotlin
Box(
    modifier = Modifier
        .fillMaxHeight()
        .background(Color.Red)
        .aspectRatio(1f)
)
```
![Screenshot](https://github.com/user-attachments/assets/d8811e7c-3854-4ea4-9efc-6b91502bcaf9)

```kotlin
@Preview
@Composable
private fun Test() {
    Surface {
        Row(modifier = Modifier.height(IntrinsicSize.Max)) {
            Box(
                modifier = Modifier
                    .fillMaxHeight()
                    .background(Color.Red)
                    .aspectRatio(1f)
            )
            Spacer(modifier = Modifier.width(8.dp))
            Column(
                modifier = Modifier
                    .weight(1f)
                    .padding(vertical = 4.dp),
            ) {
                Text(
                    text = "Top text",
                    maxLines = 1,
                    overflow = TextOverflow.Ellipsis,
                )
                Text(
                    text = "Bottom text",
                    maxLines = 1,
                    overflow = TextOverflow.Ellipsis,
                )
            }
        }
    }
}
```

**Comment by SkyD666** [comment] 2024-11-25 11:43
Looks related to this issue, but I'm not sure how it works: https://issuetracker.google.com/issues/265050176
