### ISSUE TITLE
Images disappear while in return transition

### ISSUE THREAD

**Issue by jventrib** [coil-kt/coil#650] opened 2021-02-01 19:39 UTC
Hello, 

**Describe the bug**
I'm using Jetpack Navigation with shared elements transition between fragments. When my detail fragment is returning to home fragment, images in detail fragment disappear as soon as the transition (MaterialContainerTransform) is initiated. It seems that ViewTargetRequestDelegate.dispose() is called at the beginning of the transition, causing the image to be cleared.

**Expected behavior**
I expect the images to be displayed (and fade) during the transition. This is working correctly when Glide is used instead of Coil.

**To Reproduce**
The simpliest I found to reproduce is to take the Reply app from [Material-components-android-examples](https://github.com/material-components/material-components-android-examples/tree/develop/Reply) and replace the glide image loading in BindingAdapter.kt with Coil. I see the same behaviour with my own app.

**Logs/Screenshots**

With Coil
![coil](https://user-images.githubusercontent.com/6674343/106507349-36797400-64cb-11eb-9401-a55938d7ef7a.gif)

With Glide
![glide](https://user-images.githubusercontent.com/6674343/106507427-5315ac00-64cb-11eb-8467-6ef811dfa136.gif)

**Version**
Coil 1.1.1

Thank you in advance !

**Comment by kroegerama** [comment] 2021-02-06 17:19
I'm so glad I found this bug report. At first I thought it was a bug in the material design library. [They had a bug open, too](https://github.com/material-components/material-components-android/issues/1707). But it's the fault of the image loading frameworks.

_**Keywords for anyone with the same problem:** Coil preserve image during return transition ImageView ShapeableImageView_

**Comment by colinrtwhite** [comment] 2021-02-07 21:37
I haven't tested myself, but if you set `lifecycle(activity)` on your `ImageRequest` does it work around the issue?

**Comment by kroegerama** [comment] 2021-02-07 21:44
Just tested `lifecycle(requireActivity())` but sadly didn't help.

**Comment by colinrtwhite** [comment] 2021-02-07 22:04
Setting a custom target should hopefully work around the issue:

```kotlin
val request = ImageRequest.Builder(context)
    .data(url)
    .target { imageView.drawable = it }
    .build()
imageLoader.enqueue(request)
```

**Comment by jventrib** [comment] 2021-02-08 07:31
I can confirm that setting a custom target fix the issue !
Thank you.

**Comment by kroegerama** [comment] 2021-02-08 08:11
So is this the intended way? Don't really want to put any hacks in production code :)

**Comment by artnest** [comment] 2021-02-17 20:17
> So is this the intended way? Don't really want to put any hacks in production code :)

I don't think this is the intended way, but it might be the only way to workaround the problem as it was found out here after the research: https://github.com/facebook/fresco/issues/1445#issuecomment-403879417
Maybe this can be fixed on the library side.

**Comment by ardyfeb** [comment] 2021-03-18 19:33
> Setting a custom target should hopefully work around the issue:
> 
> ```kotlin
> val request = ImageRequest.Builder(context)
>     .data(url)
>     .target { imageView.drawable = it }
>     .build()
> imageLoader.enqueue(request)
> ```

`val cannot be reassigned`

**Comment by ianhanniballake** [comment] 2021-07-11 04:08
Note that it is expected behavior from the Android framework side that any `Transition` will detach the views from their window (thus triggering any disposal associated with `onDetachedFromWindow()`).

To fix this, you'd need to disable that behavior and only rely on the `LifecycleOwner` reaching `DESTROYED` (e.g., for Fragments, the `viewLifecycleOwner` only reaches `DESTROYED` once the `Transition` fully completes). Is that possible to do right now with Coil?

**Comment by colinrtwhite** [comment] 2021-07-20 18:14
@ianhanniballake Yep, we could probably add an option disable the detach behaviour (like how using a non-`ViewTarget` disables it) though this would require enabling it manually. I'm planning to address this bug in 2.0 by removing the automatic `ImageView` clearing behaviour since it's mostly needed for bitmap pooling which is also going away.

**Closed** 2022-04-28 06:49 UTC
Labels: bug
