### ISSUE TITLE
Preloading into disk cache does not work

### ISSUE THREAD

**Issue by Patresko** [coil-kt/coil#857] opened 2021-08-11 10:49 UTC
I have follow [documentation](https://coil-kt.github.io/coil/getting_started/#preloading) for preloading images, but seems that images are not preloaded into disk cache in jetpack compose.

Im running this code in the viewModel within init block. GetImagesForCaching just add IDs of images from JSON to the array and then cacheImages() is executed to preload images with updating LinearProgressIndicator().

I have tried both options from docs .execute, enqueue. When cacheImages() is done, I put simulator to airplane mode to check if images are saved in disk cache, but no images are loaded without internet connection. If the image is shown in Compose via `Image( painter = rememberImagePainter( ... ) )` then image is available even without internet but if I tried only preload image in the background and then show without internet I have no success.
```      
// Image caching
if (preferences.getDownloadImages()) {
  viewModelScope.launch(Dispatchers.IO) {
    getImagesForCaching()
    viewModelScope.launch(Dispatchers.Main) {
      cacheImages()
    }.join()
  }
}
```

```
 private suspend fun cacheImages() {
        if (photos.distinct().isNotEmpty()) {

            isCaching.value = true

            // Loop over array of img urls
            photos.distinct().forEachIndexed { i, photo ->

                val url = "$IMG_URL$photo"

                val request = ImageRequest.Builder(context)
                    .data(url)
                    .memoryCachePolicy(CachePolicy.DISABLED)
                    .build()

                context.imageLoader.execute(request)

                progress.value = i.toFloat() / photos.size.toFloat()
            }

            isCaching.value = false
        }
    }
```

**Comment by colinrtwhite** [comment] 2021-08-17 03:36
Can you attach a sample project that reproduces the issue? It's tough to say what the issue is without one. It's possible the network headers disallow disk caching. Also please [enable logging](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging) and attach any stack traces.

**Comment by colinrtwhite** [comment] 2021-08-23 18:07
Closing this out since I'm not able to reproduce locally.

**Closed by colinrtwhite** 2021-08-23 18:07 UTC
Labels: bug
