### ISSUE TITLE
Scale SVG intrinsic size by display density

### ISSUE THREAD

**Issue by mattinger** [coil-kt/coil#566] opened 2020-10-26 18:37 UTC
I'm testing out the SVG support and loading a material design SVG:  

https://fonts.gstatic.com/s/i/materialicons/accessibility_new/v6/24px.svg

It should have an intrinsic size of 24x24, but when it's loaded the drawable has a size fo 2621x2621.
I know i can manually size it down using the .size function on the builder, but it seems like that shouldn't be necessary.

Is there something i am missing?

**Comment by mattinger** [comment] 2020-10-26 18:45
I've tried using OriginalSize but it comes out 24px by 24px instead of 24dp x 24dp

`
is OriginalSize -> {
                if (svgWidth > 0 && svgHeight > 0) {
                    bitmapWidth = svgWidth.toInt()
                    bitmapHeight = svgHeight.toInt()
                } else {
                    bitmapWidth = DEFAULT_SIZE
                    bitmapHeight = DEFAULT_SIZE
                }
            }
`

It seems like there should be some scaling involved here for screen resolution to treat the height and width as dp and not px.

**Comment by colinrtwhite** [comment] 2020-10-27 00:03
I think this is working as intended. According to the [SVG spec](https://www.w3.org/TR/SVG/coords.html#ViewportSpace):

> If the width or height presentation attributes on the outermost svg element are in user units (i.e., no unit identifier has been provided), then the value is assumed to be equivalent to the same number of "px" units.

Maybe there's another size unit that scales to the resolution? I'm not 100% sure.

**Comment by mattinger** [comment] 2020-10-27 13:30
@colinrtwhite There is no other option than PixelSize or OriginalSize.  I have temporarily solved the problem by replicating the SvgDecoder and when using OriginalSize, doign this:

val resScalingFactor = context.resources.displayMetrics.density
if (svgWidth > 0 && svgHeight > 0) {
                    bitmapWidth = (svgWidth * resScalingFactor).toInt()
                    bitmapHeight = (svgHeight * resScalingFactor).toInt()
                } else {
                    bitmapWidth = DEFAULT_SIZE
                    bitmapHeight = DEFAULT_SIZE
                }

I'm not overly happing with having to make my own SvgDecoder which has 3 line difference between the stock one though.  I'm wondering if maybe another Size type could be added (it's a sealed class)to handle this.

Maybe something like:

object OriginalSizeDp : Size()

it could be treated very much like OriginalSize except it would scale whatever image it's given by the display density.

**Comment by mattinger** [comment] 2020-10-27 13:33
PS:  It's always going to be desirable to scale an SVG in the decoder.  Once you render it to a bitmap, you'll lose the smooth scaling that SVG provides, and you'll start to get pixelation if you scale the resulting drawable.

**Comment by colinrtwhite** [comment] 2020-12-20 20:46
@mattinger What's your use case? If you want the SVG scaled, you can set the desired output size for your request using `ImageRequest.Builder.size`.

I don't think we can add an `OriginalSizeDp` since that wouldn't fit well with rasterized images (jpgs, pngs, gifs, etc.). However I might be open to adding a secondary constructor that treats an SVG's intrinsic size as `dp`. Something like: `SvgDecoder(context, scaleIntrinsicSizeByDensity = true)`.

**Comment by colinrtwhite** [comment] 2021-02-06 20:14
Going to close this out, but feel free to reopen with more info on the use case.

**Closed by colinrtwhite** 2021-02-06 20:14 UTC
Labels: enhancement

**Comment by gustavjon** [comment] 2023-02-24 15:05
I'm missing this functionality as well. I don't know the size of the SVG I'm loading so I can't really set the proper size in the ImageRequest.Builder.size method as far as I can see anyway.

**Comment by zoran-vasilic** [comment] 2023-03-17 17:15
Also missing this functionality for the implementation we use.

**Comment by Shanki070** [comment] 2023-10-19 18:34
if you want to work with original SVG size, then pass **size(Size.ORIGINAL)**

ImageRequest.Builder(context)
        .data(Uri.parse("file:///android_asset/xyz.svg"))
        .size(Size.ORIGINAL)
        .fallback(fallbackRes)
        .target { drawable ->
            layoutParams.apply {
                height = (drawable.intrinsicHeight * scalePixelToDp).toInt()
                width = (drawable.intrinsicWidth * scalePixelToDp).toInt()
            }
            setImageDrawable(drawable)
        }
