### ISSUE TITLE
In the LazyVerticalGrid  Image contentScale doesn‘t work

### ISSUE THREAD

**Issue by fansangg** [coil-kt/coil#909] opened 2021-09-27 07:30 UTC
version io.coil-kt:coil-compose:1.3.2

In the LazyVerticalGrid,when I  set `crossfade(true)`,it will make Image contentScale  doesn't work

```
Image(
                painter = rememberImagePainter(data = prefix + bean.photo, builder = {
                    //crossfade(true) if img.w > img.h contentScale doesn't work when first composition
                    placeholder(R.drawable.shape_rectangle_solid_color_50564e68)
                    error(R.drawable.shape_rectangle_solid_color_50564e68)
                }),
                contentDescription = "videoCover",
                contentScale = ContentScale.Crop, modifier = Modifier
                    .fillMaxSize()
            )
```

**Comment by colinrtwhite** [comment] 2021-09-27 17:24
Duplicate of https://github.com/coil-kt/coil/issues/855. You need to set `scale(Scale.FILL)`

**Closed by colinrtwhite** 2021-09-27 17:24 UTC
Labels: bug
