### ISSUE TITLE
Disk/Memory cache not working well on 0.9.2

### ISSUE THREAD

**Issue by kuuuurt** [coil-kt/coil#260] opened 2020-01-27 09:12 UTC
**Describe the bug**
The disk/memory cache doesn't work well in 0.9.2. 

I have a Page 1 that loads a picture from the network with
```kotlin
diskCachePolicy(CachePolicy.WRITE_ONLY)
memoryCachePolicy(CachePolicy.WRITE_ONLY)
``` 
and a Page 2 loads the same image from the cache but when I move to page 2, it reloads the same image with the same URL.

This was previously working on 0.7.0.

**Expected behavior**
It should load the images from the cache

**To Reproduce**
See Description

**Version**
0.9.2

**Comment by colinrtwhite** [comment] 2020-01-27 10:21
```kotlin
diskCachePolicy(CachePolicy.WRITE_ONLY)
memoryCachePolicy(CachePolicy.WRITE_ONLY)
```

will only write to the cache, but not read from it. It's intended behaviour that it would re-load the image from the network in a subsequent load. To have it read from the memory cache use `CachePolicy.ENABLED`.

**Comment by kuuuurt** [comment] 2020-01-27 10:32
Hello @colinrtwhite!

I forgot to mention, the `WRITE_ONLY` code is only used on Page 1. Page 2 loads with everything `ENABLED`

**Comment by kuuuurt** [comment] 2020-01-27 10:50
Also the same exact code, works on 0.7.0

**Comment by colinrtwhite** [comment] 2020-01-27 18:25
Ah gotcha. I did a quick test with the sample app and couldn't reproduce. Do you have a sample app I could use to reproduce?

**Comment by kuuuurt** [comment] 2020-01-27 18:31
Alright, I'll try to create a simple reproducer tomorrow.

For more context, I just have a Dashboard page and a Profile page. Now, the Profile page always loads it from the network for updates and uses `WRITE_ONLY` while Dashboard uses the default which is `ENABLED`. It works on the first load BUT the profile page has an update profile picture feature which uploads a new photo to the same URL. When I do that, it doesn't update so I think it has something to do with it being the same URL.

**Comment by kuuuurt** [comment] 2020-01-27 18:33
Yep. Confirmed. If I use a different URL, it works and loads it correctly but if it's the same, it loads the first one in the cache. 

The reason for having the same url for the picture is so that we won't have previous photos taking up space on the server and just save the latest one.

**Comment by colinrtwhite** [comment] 2020-02-05 23:39
@kuuuurt Are you still able to reproduce the issue on the latest version? Also have you had a chance to create a repro project?

**Comment by kuuuurt** [comment] 2020-02-07 05:19
Hello @colinrtwhite!

Sorry. I wasn't able to create a reproducer since we need a backend for it.

Here's the steps I'm taking instead:

1. Load an image with a url without the cache:
```kotlin
val url = "image-url"
imgProfilePicture.load(url) {
    diskCachePolicy(CachePolicy.WRITE_ONLY)
    memoryCachePolicy(CachePolicy.WRITE_ONLY)
}
```

2. Load on another page using the cache
```kotlin
val url = "image-url"
imgProfilePicture.load(url)
```

This works.

3. Update the picture on server-side

4. Try to load the same image without the cache:
```kotlin
val url = "image-url"
imgProfilePicture.load(url) {
    diskCachePolicy(CachePolicy.WRITE_ONLY)
    memoryCachePolicy(CachePolicy.WRITE_ONLY)
}
```

5. Load on another page using the cache
```kotlin
val url = "image-url"
imgProfilePicture.load(url)
```

This will load the first image instead of the new one.

**Comment by colinrtwhite** [comment] 2020-03-04 01:51
I ran a quick test, but wasn't able to reproduce the issue. Going to close this out, but feel free to reopen if you can create a project that reproduces the issue.

**Closed by colinrtwhite** 2020-03-04 01:51 UTC
Labels: bug, needs info
