### ISSUE TITLE
ImageView flashes when pull down to refresh Recycler

### ISSUE THREAD

**Issue by caiyoufei** [coil-kt/coil#511] opened 2020-08-28 16:08 UTC
Only appeared in version 0.12.0

![异常](https://user-images.githubusercontent.com/11989916/91589048-4cff2a80-e983-11ea-8e17-f87c09c6d2ac.gif)

**Comment by colinrtwhite** [comment] 2020-08-28 18:17
Duplicate of #280.

**Closed by colinrtwhite** 2020-08-28 18:17 UTC
Labels: bug

**Comment by caiyoufei** [comment] 2020-08-29 02:17
Thank you very much
