### ISSUE TITLE
Image flickers when url changes for rememberImagePainter

### ISSUE THREAD

**Issue by cj1098** [coil-kt/coil#928] opened 2021-10-08 00:17 UTC
Currently I'm using a library to reorder items in a LazyColumn. The library works and functions as expected. The issue I'm running into is that when an item is reordered in the list, it causes a recomposition because my state has changed since the position of the item has changed. This is fine, but when items in my list recompose, they might have different urls so it tries to load the new image for both items that had their positions change. This causes a flicker as it tries to load new images. I've tried to use caching to prevent `rememberImagePainter` from having to go fetch the image again but I don't think that's how that works. I've tried to prevent the request from going through by providing an ExecuteCallback that returned false if the state wasn't empty and that didn't work either.

I would expect to be able to configure coil to not re-load an image when a url changes but instead use a cached version if it exists.

I'm using version 1.3.2 and it's not device specific.

**Comment by cj1098** [comment] 2021-10-08 23:19
Sure! I'll setup a sample project for this and post it sometime this weekend for you guys next week!

**Comment by colinrtwhite** [comment] 2022-03-07 02:06
@cj1098 This is fixed in `2.0.0-rc01`.

**Closed by colinrtwhite** 2022-03-07 02:06 UTC

**Comment by cj1098** [comment] 2022-04-15 16:08
> 

@colinrtwhite Thank you for looking at this and fixing it! Someone on our team upgraded and I believe it fixed it. I am curious if you could share what the actual fix was? Looked through the changelog but couldn't discern what would've fixed it. Disk caching done by Coil instead of okhttp?

**Comment by Swirastlynn** [comment] 2022-05-18 12:22
I can still observe flickering on `2.1.0`. It doesn't always happen, but quite often. I haven't set any caching, all setup is default. 

Code:
```
 val imageRatio = 9f / 16f

 LazyColumn(
            modifier = Modifier
                    .fillMaxSize()
                    .background(AppTheme.colors.itemBackground)
    ) {
        item {
            val screenWidth = LocalConfiguration.current.screenWidthDp.dp
            AsyncImage(
                    model =  detailsInfo?.landscapeImageUrl ?: "", // this change between recompositions is problematic
                    placeholder = ColorPainter(colorResource(id = R.color.details_header_bg)),
                    contentDescription = detailsInfo?.title ?: "placeholder",
                    modifier = Modifier.size(screenWidth, screenWidth * imageRatio)
            )
        }
   ...
   }
   ```

**Comment by iamutkarshtiwari** [comment] 2022-08-25 13:43
Facing the same issue as mentioned by @Swirastlynn with `2.1.0` even when disk and memory caching is applied. I happen to be using Coil in LazyRow.

**Comment by volkansahin45** [comment] 2022-12-28 09:23
I feel like your problem might be you are not using key. https://developer.android.com/jetpack/compose/lists#item-keys

**Comment by vanniktech** [comment] 2024-11-22 14:02
In case anyone stumbles upon this now, in my case this was caused by using `crossfade(true)` and having a placeholder and the real image for which the crossfade animation caused the flickering.

**Comment by Ddudduu** [comment] 2025-08-26 16:47
@vanniktech It worked in my case too.. thank you so much
