### ISSUE TITLE
Didn't load image from disk cache if it loaded with empty string header

### ISSUE THREAD

**Issue by mmarashan** [coil-kt/coil#1565] opened 2022-12-12 08:21 UTC
**Describe the bug**
If server returns image with empty string in header, then image can't load from disc next session

**To Reproduce**
If server returns image with empty string in header, then image can't load from disc next session.

**Logs/Screenshots**
java.lang.IllegalArgumentException: name is empty
at okhttp3.Headers$Companion.checkName(Headers.kt:438)
at okhttp3.Headers$Companion.access$checkName(Headers.kt:362)
at okhttp3.Headers$Builder.addUnsafeNonAscii(Headers.kt:270)
at coil.util.-Utils.addUnsafeNonAscii(Utils.kt:239)
at coil.network.CacheResponse.<init>(CacheResponse.kt:29)
at coil.fetch.HttpUriFetcher.toCacheResponse(HttpUriFetcher.kt:255)

**Version**
Coil 2.2.2

**To Fix**
if coil.util.Utils rewrite

internal fun Headers.Builder.addUnsafeNonAscii(line: String) = apply {
    val index = line.indexOf(':')
    require(index != -1) { "Unexpected header: $line" }
    val name = line.substring(0, index).trim()
    val content = line.substring(index + 1)
    require(name.isNotEmpty()) { "Header name can't be empty" }
    addUnsafeNonAscii(name, content)
}

**Comment by colinrtwhite** [comment] 2023-02-08 01:54
Hmm `addUnsafeNonAscii` already enforces that `name` isn't empty so it already shouldn't be possible to add an entry with an empty header. Maybe it was added to the cache in a previous version?

**Comment by colinrtwhite** [comment] 2023-03-06 20:13
Closing as this should already be covered and I'm not able to reproduce locally.

**Closed by colinrtwhite** 2023-03-06 20:13 UTC
