### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by mohamedmelfiky** [coil-kt/coil#500] opened 2020-08-19 13:29 UTC
**Describe the bug**
I have a project using epoxy, constraintLayout, viewPager2 and coil. When i try to load image it goes in infinite loop.

**Expected behavior**
Not to go in infinite loop

**To Reproduce**
How can we reproduce this?
this is a sample project to reproduce https://github.com/mohamedmelfiky/BugSample.git

**Version**
What library version are you using? Also does this occur on a specific API level or Android device.
Coil 1.0.0-rc1

**Notes**
I tried a lot of things and some have worked any of this worked
1 - when i make coil ImageViewTarget don't setImageDrawable in onStart and onClear it work
2 - when i change constraintLayout of the viewPager parent to FrameLayout it work
3 - when i change constraintLayout of the epoxyRecyclerView parent to FrameLayout it work

i expect it to be a constraintLayout Bug but is coil should do this in that scenario.

**Comment by colinrtwhite** [comment] 2020-09-08 00:34
Thanks for reporting this. This appears to be a bug with `ConstraintLayout` (tested against `2.0.1`) as it's possible to reproduce it without Coil by replacing `CustomView.setData` with the following code:

```kotlin
@ModelProp
fun setData(data: String?) {
    binding.newTaskOwnerProfilePicImgV.setImageDrawable(null)
    binding.newTaskOwnerProfilePicImgV.post {
        binding.newTaskOwnerProfilePicImgV.setImageResource(R.mipmap.ic_launcher)
    }
}
```

Also, as you mentioned this can be fixed by replacing the `ConstraintLayout` with `FrameLayout`. The issue is `ConstraintLayout` is causing the view to be rebound even though the `ImageView`'s size is not changed when setting a new `Drawable` on it.

Fortunately, Coil `0.13.0` and `1.0.0-rc2` works around this by synchronously checking the memory cache (by default).

I'm not 100% sure it isn't an Epoxy bug either, however [please report it](https://issuetracker.google.com/issues/new?component=323867&template=1023345) to the ConstrainLayout team just in case!

**Closed by colinrtwhite** 2020-09-08 00:34 UTC
Labels: bug, help wanted

**Comment by mohamedmelfiky** [comment] 2020-09-08 02:22
Thanks and appreciate your work a lot.
I will try to report it.
