### ISSUE TITLE
Function crossfade(true) didnt work.

### ISSUE THREAD

**Issue by Starscream9559** [coil-kt/coil#104] opened 2019-09-17 23:26 UTC
So this is my first time trying this library. Wanna see how it's better than Glide and others and suddenly bumped into this, which I believe a bug. I'm using crossfade() for the fading up animation image loader. It seems that the image only load once. If I go Back screen, and re enter the activity, the image is not loaded anymore. Here is how I specify my code;

```
imageView.load("www.google.com/image"){
crossfade(true)
}
```
Note that on the arguement TRUE in the bracket, in my IDE it wrote as **enable : true** .

**To Reproduce**
Enter the Activity, once inside, go Back. Then re enter again. 

**Expected behavior**
Some image loaded, some not.

**Logs/Screenshots**
![image](https://user-images.githubusercontent.com/12114864/65086726-77abd980-d9e5-11e9-9fee-9c1b9419b0d5.png)

**Library version**
0.7.0

**Comment by colinrtwhite** [comment] 2019-09-17 23:29
Do you have a sample application/snippet that can reproduce this? Thanks

**Comment by Starscream9559** [comment] 2019-09-21 16:29
I send screenshot of this dummy app first. for your first thought. FYI, Internet permission given. Java8 bytecode enabled.

![DeepinScreenshot_dde-desktop_20190922002719](https://user-images.githubusercontent.com/12114864/65376221-10857200-dcd0-11e9-8218-ef5bb3945be9.png)

**Comment by colinrtwhite** [comment] 2019-09-21 21:16
Can you enable logging with `CoilLogger.setEnabled(true)` and post the logs?

**Comment by Starscream9559** [comment] 2019-09-24 09:20
A repo set-up for testing. Try take a look.
https://github.com/Starscream9559/DuumyApp4CodeTesting.git

**Comment by colinrtwhite** [comment] 2019-09-30 18:12
@Starscream9559 Thanks for the sample project, however I'm not able to reproduce the issue with it. If I navigate forward to an Activity and back, the image still shows correctly.

**Comment by colinrtwhite** [comment] 2019-10-01 22:06
Going to close this, but feel free to reopen if I've missed something in the sample project.

**Closed by colinrtwhite** 2019-10-01 22:06 UTC
Labels: bug, needs info

**Comment by Queatz** [comment] 2020-12-16 03:01
It seems like crossfade does not happen if it has loaded the image from memory.
