### ISSUE TITLE
NPE in SystemCallbacks.onTrimMemory

### ISSUE THREAD

**Issue by Jeff11** [coil-kt/coil#1211] opened 2022-03-23 11:39 UTC
Got a few crashes in 2.0.0-rc01 on Android 8-12.
Firebase reports that app was always in background 

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object sb.d.getValue()' on a null object reference
       at coil.RealImageLoader.getMemoryCache(RealImageLoader.kt:80)
       at coil.RealImageLoader.onTrimMemory$coil_base_release(RealImageLoader.java:213)
       at coil.util.SystemCallbacks.onTrimMemory(SystemCallbacks.kt:52)
       at android.app.Application.onTrimMemory(Application.java:306)
       at android.app.ActivityThread.handleTrimMemory(ActivityThread.java:6653)
       at android.app.ActivityThread.access$1400(ActivityThread.java:274)
       at android.app.ActivityThread$ApplicationThread.lambda$scheduleTrimMemory$0(ActivityThread.java:1742)
       at android.app.-$$Lambda$ActivityThread$ApplicationThread$tUGFX7CUhzB4Pg5wFd5yeqOnu38.accept(-.java:8)
       at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:271)
       at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:195)
       at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:86)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by colinrtwhite** [comment] 2022-03-23 18:28
Hmm are you using an alpha version of the Android Gradle Plugin? Looking at the code it shouldn't be possible to trigger an NPE [here](https://github.com/coil-kt/coil/blob/main/coil-base/src/main/java/coil/RealImageLoader.kt#L213) without R8 manipulating the code incorrectly.

Are you using any custom R8 rules that could rewrite this code as well?

**Comment by colinrtwhite** [comment] 2022-03-24 19:39
None of those rules look like they should cause an NPE in Coil. Interestingly we're seeing the same crash at Instacart, though very low volume. My suspicion is R8 is manipulating the code incorrectly since it only occurs in release builds and we're doing a null check.

**Comment by colinrtwhite** [comment] 2022-03-24 20:11
Opened https://github.com/coil-kt/coil/pull/1215 to hopefully guard against the crash. I don't see anything related in the [R8 bug tracker](https://issuetracker.google.com/issues?q=componentid:326788%20status:open&s=modified_time:desc), but I'd like to figure out the root cause instead of just working around it.

**Comment by colinrtwhite** [comment] 2022-04-11 04:48
@Jeff11 Are you still seeing the exception? It stopped 2 weeks ago for us, though I'm not sure about the root cause. It's likely updating our build tools or AGP fixed the issue.

**Comment by Jeff11** [comment] 2022-04-11 08:02
Last occurence was

**Comment by colinrtwhite** [comment] 2022-05-11 05:02
Closing this out as the work-around seems to have fixed the issue. My suspect for the root cause is still R8 given this only occurs in release builds. I'll revisit the work-around later and see if it's possible to be removed.

**Closed by colinrtwhite** 2022-05-11 05:02 UTC
Labels: help wanted
